[project]
name = "trabalho-1-panorama"
version = "0.1.0"
description = "Panoramas a partir de fotos fora de ordem (Trabalho 1, MO446)"
readme = "README.md"
authors = [
    { name = "Beatriz Celante", email = "beatrizcelante@gmal.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.24",
    "opencv-python>=4.5",
    "rawpy>=0.19",
    "scipy>=1.10",
]

[dependency-groups]
x4 = [
    "torch>=2.4",
    "lightglue @ git+https://github.com/cvg/LightGlue.git",
]

[tool.uv]
default-groups = ["x4"]
